### ISSUE TITLE
OPD Design for Diagnosis and treatment

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-opd#23]
There is a need for a design for the OPD Diagnosis treatment with the categories Tests, Diagnosis and Treatment, Medical/Drugs as per data dictionary https://docs.google.com/spreadsheets/d/1h2JrUCi0geT1NQm63bEicT0knKaOYe-LJ-gEFlODETc/edit#gid=153801718 

17/09 Discussions based on meeting 
A way of searching should be provided, 
Initial option is to have the auto complete widget implementation
If not available use the lookup function
Have repeating groups where the test and result are grouped together, diagnosis and disease code, medicine/dosage and duration as another group
Have an option to show the lists should be shown in their entirety as a link beneath the search field, choice to be selected into the repeating group
Use common test list from ANC as we await the list from HISP
Use relevance to determine possible responses to the tests

**Comment by ekigamba** [comment]
@rowo This is in-order and good as per myself

**Comment by rowo** [comment]
@ekigamba yes, I'm good with this. As you are implementing, when you know more about how you are going to build it, let me know of any open decisions and we can chat through any details

**Comment by hmakandi** [comment]
@rowo Please provide the same for Tests and Medication/Drugs as well as the treatment. The mockups only cover Diagnosis...

**Comment by ekigamba** [comment]
@rowo Definitely will

**Comment by rowo** [comment]
same design patterns, different content from the spreadsheet. not sure if the packSize is necessary.

![List - browse, no first item Copy](https://user-images.githubusercontent.com/1584163/66884155-4996c680-ef9e-11e9-85de-8d45d3e3aeaf.png)
![List - on open Copy](https://user-images.githubusercontent.com/1584163/66884158-4a2f5d00-ef9e-11e9-89bd-c1e351ecfccd.png)
![Form-long list Copy 2](https://user-images.githubusercontent.com/1584163/66884159-4a2f5d00-ef9e-11e9-93d8-48b06f0680fb.png)
![Form-long list Copy](https://user-images.githubusercontent.com/1584163/66884160-4a2f5d00-ef9e-11e9-8cd0-e7c77561dd2c.png)

**Comment by cafootitt** [comment]
I think the dosage/duration is per medicine or treatment, so we might have to treat it like a repeat group.

**Comment by rowo** [comment]
@cafootitt @hmakandi will all medicine or treatments have individual dosage/durations or will we need some logic to drive that?

**Comment by rowo** [comment]
@ekigamba do you see an issue with the screen below that addresses [Carolyn's comment](https://github.com/OpenSRP/opensrp-client-opd/issues/23#issuecomment-542656914)? Here, each new medicine gets dose and duration questions. [Previous comment](https://github.com/OpenSRP/opensrp-client-opd/issues/23#issuecomment-544337407) was asking if all of them do or just some of them. Another option might be to nest the medicine list layer at a third sublevel.

<img src="https://user-images.githubusercontent.com/1584163/67211160-49585a00-f3e8-11e9-8652-6d886b6fcd72.png" width="300">

**Comment by hmakandi** [comment]
@rowo The comments by @cafootitt are relevant, each medicine has to have its own dosage and duration so the last design would be more appropriate.

Please help identify the transition buttons between the different aspects. Will we have a next button?Tabs? How is the transition from one form to another?

**Comment by rowo** [comment]
@hmakandi Cool. Sure I can do that but was wondering about the two directions in https://github.com/OpenSRP/opensrp-client-opd/issues/23#issuecomment-544525918. I updated the description a bit more and reached out to @ekigamba to see if it made sense. I can hop on a quick call to discuss it.

**Comment by ekigamba** [comment]
**UPDATE** We just discussed this with @rowo and @bennsimon. Direction B seems less effort and better

**Comment by rowo** [comment]
![Treatment01](https://user-images.githubusercontent.com/1584163/67487691-608f8580-f63c-11e9-85b1-4d1d219ffb9d.png)
![Treatment02](https://user-images.githubusercontent.com/1584163/67487688-5ff6ef00-f63c-11e9-803d-10e83e22d945.png)
![Treatment03](https://user-images.githubusercontent.com/1584163/67487687-5ff6ef00-f63c-11e9-84b2-95611603b04c.png)
![Treatment04](https://user-images.githubusercontent.com/1584163/67487690-608f8580-f63c-11e9-95c6-51eec3dfa134.png)
![Treatment05](https://user-images.githubusercontent.com/1584163/67487689-608f8580-f63c-11e9-905c-bbed1c0ad4fe.png)

**Comment by hmakandi** [comment]
Confirmed and well executed.
